### ISSUE TITLE
Compile without wrapper function?

### ISSUE THREAD

**Issue by CiaraBurkett** [technet/brackets.coffeescriptcompiler#1]
This is a great Brackets extension, but I'm using it with the Phaser game engine and the wrapper function doesn't work with Phaser's state system. Do you have plans for additional compile options or should I just compile from the command line?

**Comment by technet** [comment]
I'm not familiar with Phaser game engine however how do you think adding additional compile options would help to solve that issue you have?. and this wrapper function was required in order to work it in the brackets environment, but if that game engine is based on nodejs you could simply install cofeescript using npm and then do something like following

```
var cf = require("coffee-script");
alert(cf.VERSION)    // see coffee script version
alert(cf.compile("cubes = (math.cube num for num in list)"));   // compile coffeescript
```

**Comment by CiaraBurkett** [comment]
Well, if it won't work with Brackets without the wrapper function, then there's no point in adding more compile options. I'm compiling via CLI for now, may go with a static site builder.

Thanks for getting back quickly.
